Support for encoding java.lang.Short numeric values
Previously Short instances of Number were being cast as Float, which would
cause:

  java.lang.ClassCastException: java.lang.Short cannot be cast to
    java.lang.Float